### ISSUE TITLE
Map tiles flicker when vehicle tracking on iOS

### ISSUE THREAD

**Issue by stdavis** [agrc/roadkill-mobile#171]
It appears to be [this bug](https://github.com/react-native-maps/react-native-maps/issues/3969) to me. The drawing of the vehicle tracking polyline is the thing that triggers the bug.

This does not happen if we use Google Maps, but Google Maps on iOS [do not support offline tile caching](https://github.com/react-native-maps/react-native-maps/pull/3789#issuecomment-977053138).

**Comment by stdavis** [comment]
This bug is not present on Jessie's phone: 15.0.2 / iPhone 11

**Comment by nathankota** [comment]
The bug is present on T.J.'s phone: 15.4 / iPhone 7

**Comment by nathankota** [comment]
possibly related to (and maybe resolved by) #187

**Comment by nathankota** [comment]
fixed

**Comment by stdavis** [comment]
Jessie is still seeing this. I wonder if it's a problem with iOS < 16.

**Comment by stdavis** [comment]
Upgrading to iOS 16 fixed this for both Jessie and Rhianna.

**Comment by stdavis** [comment]
Since this is only present on < iOS 16, I propose that we ignore this bug and spend time on higher priorities. @nathankota Agreed?

**Comment by nathankota** [comment]
agreed
